name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20, 22, 23]
        os: [macos-14, macos-15]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/package-lock.json
      - uses: actions/checkout@v4
      - name: npm install, build, and test
        env:
          CI: true
        run: |
          npm ci
          npm run lint
          npm run build
          npm test
